### ISSUE TITLE
Clarify documentation related to dictionaries originating from YAML variable files

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework/robotframework#2121]
Is it possible to get more examples for dictionaries in yaml style?

e.g. I'm running into SyntaxError when I use this in a .yaml file:

```yaml
SO_BUTTON:
   Empty Basket: xpath=//div[@class="basket__teaser basket__teaser--empty"]
```
and call it with this keyword from RF:
```robot
Element Should Be Visible   | ${SO_BUTTON.Empty Basket}
```

Error Log: 

```
Resolving variable '${SO_BUTTON.Empty Basket}' failed: SyntaxError: unexpected EOF while parsing (<string>, line 1)
```

I have to use underscore in each file (.yaml and .robot) to make it work: `Empty_Basket`

**Comment by Tset-Noitamotua** [comment]
Another error example:

```yaml
SO_PRODUCT_GROUP:
  Group_A_Active: xpath=//li[contains(@class,'product-filter__item--active')]
```
Called from RF with: `Page Should Contain Element | ${SO_PRODUCT_GROUP.Group_A_Active}`

Fails with:
`ScannerError: mapping values are not allowed here
  in "C:\path_to\my_file.yaml", line 36, column 36`

**Comment by pekkaklarck** [comment]
It seems that you are using invalid YAML syntax and your extended variable usage uses invalid Python syntax. We definitely cannot explain the whole Python or YAML syntax in User Guide or anywhere. User Guide already has a link to http://www.yaml.org that contains the official YAML specification.

The above doesn't mean additional examples and explanations couldn't be added to cover common problems. Please submit pull requests if you have concrete enhancement ideas.

**Comment by Tset-Noitamotua** [comment]
```yaml
string:   Hello, world!
integer:  42
list:
  - one
  - two
dict:
  one: yksi
  two: kaksi
  one two: foo bar
  three four five: foodoo bar
```

Are the last two lines legal syntax?

**Comment by pekkaklarck** [comment]
I don't know. I don't have much YAML experience myself. Did you read the spec? Did you try parsing the YAML file using some other tool than Robot?

**Comment by pekkaklarck** [comment]
Do you have ideas how to improve the docs?

**Comment by Tset-Noitamotua** [comment]
I used YAML for the firts time and I did speed read the spec only. I didn´t see any examples in the spec for key containing spaces. I would be interessting to know if spaces are allowed, then one could add some more examples to the docs.

**Comment by jussimalinen** [comment]
If you could find or produce some good examples to add to the documentation, please provide a pull request. There is a link to yaml specification from the documentation, but if you find a better link, we can also consider adding that.

**Comment by Tset-Noitamotua** [comment]
I found this examples in [PyYAML docs](http://pyyaml.org/wiki/PyYAMLDocumentation) which let me assume that 'spaces' should be allowed in 'keys':
- Section - [Block sequences](http://pyyaml.org/wiki/PyYAMLDocumentation#Blocksequences)
```yaml 
# YAML block sequences
left hand:
- Ring of Teleportation
- Ring of Speed

right hand:
- Ring of Resist Fire
- Ring of Resist Cold
- Ring of Resist Poison
```

```python
# Python block sequences
{'right hand': ['Ring of Resist Fire', 'Ring of Resist Cold', 'Ring of Resist Poison'],
'left hand': ['Ring of Teleportation', 'Ring of Speed']}
```

- Section - [Block mappings](http://pyyaml.org/wiki/PyYAMLDocumentation#Blockmappings)
```yaml
# YAML block mapping
base armor class: 0
base damage: [4,4]
plus to-hit: 12
plus to-dam: 16
plus to-ac: 0
```
```python 
# Python block mapping
{'plus to-hit': 12, 'base damage': [4, 4], 'base armor class': 0, 'plus to-ac': 0, 'plus to-dam': 16}
```

Unfortunately the most interesting example in my case does not contains any spaces. But I guess it works analogously to the examples above and could also contain spaces(?):
```yaml
# YAML nested block mapping
hero:
  hp: 34
  sp: 8
  level: 4
orc:
  hp: 12
  sp: 0
  level: 2
```
```python
# Python nested block mapping
{'hero': {'hp': 34, 'sp': 8, 'level': 4}, 'orc': {'hp': 12, 'sp': 0, 'level': 2}}
```

But as I stated initially using spaces in the keys did not work me. 

Lets say I have:

```yaml
# YAML
hero:
  health points: 34
  strength points: 8
```
How should I access 'health points' from RF? Would `${hero.health points}`be correct?

**Comment by pekkaklarck** [comment]
The problem is that `${var.attr}` syntax is evaluated in Python and the `attr` part must be a valid Python attribute name. Python attributes cannot contain spaces and thus `${hero.health points}` fails. You can either change the attribute to `health` or `heath_points` or access it like `${here['health points']}` or `&{hero}[health points]`. Notice that in the former example you must use quotes around `health points` and in the latter you must not.

The above topic ought to be explained, at least to some detail, in the Extended variables section. Concrete enhancement ideas to it, including possibly linking that section from YAML variables section, are appreciated.

**Comment by Tset-Noitamotua** [comment]
Thank you very much, Pekka. That is exact the information I was looking for. 

Next question that might arise (at least for python noobs like me) is "What´s with the `var` part of  `${var.attr}`? Can it contain spaces and if yes how would the syntax to access it look like?"

```yaml
# YAML
super hero:
  health points: 100
  strength points: 100
```
Would this be correct to access the value of "health points"?  `&{super hero}[health points]`

**Comment by pekkaklarck** [comment]
This ought to be explained in the extended variable syntax section.

**Comment by pekkaklarck** [comment]
So, what should we do with this issue? Is there something we should add to docs?

**Comment by Tset-Noitamotua** [comment]
In my opion at least something like this ...

Recent example in docs section [Variable file as YAML:] (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-file-as-yaml)
>```yaml
string:   Hello, world!
integer:  42
list:
  - one
  - two
dict:
  one: yksi
  two: kaksi
```
...
If the above YAML file is imported, it will create exactly the same variables as the following variable table:
```robot
*** Variables ***
${STRING}     Hello, world!
${INTEGER}    ${42}
@{LIST}       one         two
&{DICT}       one=yksi    two=kaksi
```


Suggested update of example above:
```yaml
string:   Hello, world!
integer:  42
list:
  - one
  - two
dict:
  one: yksi
  two: kaksi
  three four: foobar

# and this one if it is legal, at all
dict name with spaces:
  one: yksi
  two three: kaksi
```
...

```robot
*** Variables ***
${STRING}     Hello, world!
${INTEGER}    ${42}
@{LIST}       one         two
&{DICT}       one=yksi    two=kaksi    three four=foobar

# and this one if it is legal, at all
&{DICT NAME WITH SPACES}    one=yksi    two three=kaksi
```


Recent explanation of how to access variables from yaml file:
> Mappings used as values are automatically converted to special dictionaries
that are used also when creating dictionary variables in the variable table.
Values of these dictionaries are accessible as attributes like `${DICT.one}`.

Suggested update of explanation:
" ... Values of these dictionaries are accessible as attributes like `${DICT.one}`. If your attributes contain spaces like in `three four` use `${dict['three four']}` or `&{dict}[three four]` to access their values. Notice that in the former example you must use quotes around `three four` and in the latter you must not." + if applicable an example for `&{DICT NAME WITH SPACES}`.
