### ISSUE TITLE
How to handle complex data structure in yaml variable file.

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2224]
Hi 

I'm glad to see robotframework support yaml as first class variable file.
I tried below simple data structure and used ${},@{},&{} syntax, they worked fine:
```
string:   Hello, world!
integer:  42
list:
  - one
  - two
dict:
  one: yksi
  two: kaksi
```

But if I want to handle complex data structure like list contains list , list contains dict, dict contains list. 
For example list contains list, how I can use robotframework to handle this, it didn't work like I want to use the nested list @{companyProfileInfo}[6]:
```
companyProfileInfo:
 - lulu Ltd.
 - "1546587995"
 - "23233223"
 - uu@sap.com
 - "3234235445454"
 - "3242342343"
 -  
  - add
  - "20000"
  - "15845210235"

```

Highly recommend that you can give robotframework samples for above three complex data structures.

B.R.
Luis
