### ISSUE TITLE
Import Variables from YAML file may generate variables with illegal Python names

### ISSUE THREAD

**Issue by pianofab** [robotframework/robotframework#4697]
Importing variables directly from a YAML file is a nice feature. However, tools like [stress-ng](https://github.com/ColinIanKing/stress-ng) generate YAML files containing top-level keys containing hyphens (dashes) which are interpreted as the minus sign and therefore generate inaccessible variables (believe me, I tried).

To the best of my knowledge, a YAML file containing such keys is valid.
Therefore, the burden is on Robot to allow importing such YAML files, perhaps changing the '-' to '_' during import.

A simple way to generate one such YAML file is:

`stress-ng --matrix 0 --tz -t 5 --times --metrics --yaml matrix.yaml`

See also #https://github.com/robotframework/RIDE/issues/1945

**Comment by pianofab** [comment]
```
system-info:
      stress-ng-version: 0.13.12
      run-by: fab
      date-yyyy-mm-dd: 2023:03:23
      time-hh-mm-ss: 10:05:14
      epoch-secs: 1679591114
      hostname: austin-bbq
      sysname: Linux
      nodename: austin-bbq
      release: 5.15.0-67-generic
      version: '#74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023'
      machine: x86_64
      uptime: 1536302
      totalram: 33567764480
      freeram: 18671575040
      sharedram: 11964416
      bufferram: 4096724992
      totalswap: 1023406080
      freeswap: 1020829696
      pagesize: 4096
      cpus: 8
      cpus-online: 8
      ticks-per-second: 100

thermal-zones:
    - stressor: matrix
      acpitz0:   27.80
      acpitz1:   28.80
      x86_pkg_temp:   37.08

```
