### ISSUE TITLE
allow specifying options in `pyproject.toml`

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4843]
so instead of `robot --outputdir output --listener Foo --listener Bar` you could define it like this:
```toml
[tool.robot]
outputdir = "output"
listeners = ["Foo", "Bar"]
```
