### ISSUE TITLE
Use better theme with API docs at Read The Docs

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#5039]
Robot API docs are, at least currently, hosted at https://robot-framework.readthedocs.io/. The default theme used there has changed so that the navigation bar on left doesn't show sub modules as earlier. Compare, for example, these:
https://robot-framework.readthedocs.io/en/v6.1.1/autodoc/robot.api.html
https://robot-framework.readthedocs.io/en/v7.0/autodoc/robot.api.html

We already had #5034 about changing the theme to the one that was used earlier, but it had some problem and [building API docs failed](https://readthedocs.org/projects/robot-framework/builds/23257790/).

**Comment by manykarim** [comment]
Seems like readthedocs changed their original approach a bit.
[First ](https://blog.readthedocs.com/python-core-requirements-changed/)they wanted to keep older projects (created <August2023) untouched - but [then ](https://blog.readthedocs.com/defaulting-latest-build-tools/)decided to also remove several dependencies from them (including sphinx and the sphinx-rtd-theme).

Solution from article above:
https://blog.readthedocs.com/defaulting-latest-build-tools/

A basic configuration example to work from would include the following files:

`.readthedocs.yaml`

```
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

 python:
   install:
     - requirements: docs/requirements.txt
```

`docs/requirements.txt`

```
sphinx==6.2.1
sphinx-rtd-theme==1.2.2
pillow==5.4.1
mock==1.0.1
commonmark==0.9.1
recommonmark==0.5.0
```
