### ISSUE TITLE
`robot --version` causes "Error: Process completed with exit code 251." in GitHub Actions

### ISSUE THREAD

**Issue by alundiak** [robotframework/robotframework#5184]
I'm new to Robot framework, and I tried to search similar issue, but haven't fount yet.

So,

When I add `robot --version` to my YAML file it then cause Pipeline to fail. No matetr where - just after instalation or just before running tests.

![Screenshot 2024-08-15 at 11 39 32](https://github.com/user-attachments/assets/9050d5cf-266e-41a9-9b81-b72a9d585fd8)

To make sure Robot is really installed I execute `$ pip show robotframework` => 
```
Name: robotframework
Version: 7.0.1
```

And all good.

But next line where `robot --version` is, cause this error:

```
Robot Framework 7.0.1 (Python 3.12.4 on linux)
Error: Process completed with exit code 251.
```

And then flow doesn't go and and pipeline fails.
When I REMOVE `robot --version` from YAML all good - code execution follows - TESTS passed.

Note that locally, MacOS, single command `robot --version` works OK. 
```bash
$ robot --version
Robot Framework 7.0.1 (Python 3.12.5 on darwin)
```

BUT, when I chain commands, then it looks like ONLY first command is executed:

```bash
$ robot --version && robot --loglevel DEBUG --outputdir results tests/

Robot Framework 7.0.1 (Python 3.12.5 on darwin)
```

and no tests executions.

Here is my YAML:

```yaml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify dependencies
      run: |
        pip show robotframework

    - name: Verify Robot Version
      run: |
        robot --version
        
    - name: Run Robot Framework tests
      run: |
        robot --loglevel DEBUG --outputdir results tests/
```

Full YAML [here](https://github.com/alundiak/robot-testcase/blob/main/.github/workflows/robot-python-tests.yml), but I do not guarantee my repo will be public long time.
